import { Inter} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Header from "@/components/ui/header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";
const inter = Inter ({subsets:["lantin"]});


export const metadata = {
  title: "PrepPilot Career Guide",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"suppressHydrationWarning>
      <body
        className={`${inter.className}`}
      >
       <ClerkProvider appearance={{baseTheme:dark}}>
         <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {/*header*/}
            <Header />
            <main className="min-h-screen">{children}</main>
            <Toaster richColors/>
            {/*footer 50 is opacity*/}
            <footer className="bg-muted/50 py-12"> 
              <div className="container mx-auto px-4 text-center text-gray-200">
                <p>made with Love</p>
              </div>
            </footer>
          </ThemeProvider>
         </ClerkProvider>  
      </body>
    </html>
  );
}
